rootProject.name = "testmints"
include("minassert")
include("standard")
include("async")
include("action")
include("action-async")
include("minspy")
include("mindiff")
include("report")
include("minreact")
include("minenzyme")
include("react-data-loader")
