version: 2.1
jobs:
  build-linux:
    docker:
      - image: cimg/openjdk:17.0
        environment:
          GRADLE_OPTS: -XX:+HeapDumpOnOutOfMemoryError
          _JAVA_OPTIONS: "-Xmx3g"
    steps:
      - run: "sudo apt-get update"
      - run: "sudo apt-get install libncurses5"
      - checkout
      - restore_cache:
          key: jsmints-cache-10-{{ .Branch }}
      - run: "./gradlew check release closeAndReleaseSonatypeStagingRepository --stacktrace"
      - save_cache:
          key: jsmints-cache-10-{{ .Branch }}
          paths:
            - buildSrc/build
            - "~/.gradle"
            - "~/.konan"
            - ".gradle"
      - store_artifacts:
          path: build/test-output
      - store_test_results:
          path: build/test-output
  update-libs:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - run: "sudo apt-get update"
      - run: "sudo apt-get install libncurses5"
      - checkout
      - run: "./gradlew :jsmints-plugins:useLatestVersions useLatestVersions"
      - run: "./gradlew model"
      - run: "./gradlew check release --stacktrace"
      - store_artifacts:
          path: build/test-output
      - store_test_results:
          path: build/test-output
      - run: "git add ."
      - run: "git config user.email \"robert.f.murdock@gmail.com\""
      - run: "git config user.name \"CircleCI in a RoB Suit\""
      - run: "git commit -m '[patch] Automatic dependency update.' || echo 'Ignoring no changes'"
      - run: "git push"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-linux
  update-libs:
    triggers:
      - schedule:
          cron: "0 15 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update-libs
