version: 2
jobs:
  build-linux:
    docker:
      - image: circleci/openjdk
    steps:
      - checkout
      - restore_cache:
          key: testmints-cache-5-{{ .Branch }}
      - run: "./gradlew check release --stacktrace"
      - save_cache:
          key: testmints-cache-5-{{ .Branch }}
          paths:
            - buildSrc/build
            - "~/.gradle"
            - "~/.konan"
            - ".gradle"
      - store_artifacts:
          path: build/test-output
      - store_test_results:
          path: build/test-output
      - persist_to_workspace:
          root: ./
          paths:
            - "*"
  build-mac:
    macos:
      xcode: "11.3.0"
    steps:
      - checkout
      - restore_cache:
          key: testmints-mac-cache-2-{{ .Branch }}
      - run: "git tag -d $(git describe) || echo 'no fail'"
      - run: "./gradlew -P release-target=mac release bintrayUpload"
      - save_cache:
          key: testmints-mac-cache-2-{{ .Branch }}
          paths:
            - "~/.gradle"
            - "~/.konan"
            - ".gradle"
      - store_artifacts:
          path: build/test-output
      - store_test_results:
          path: build/test-output
      - persist_to_workspace:
          root: ./
          paths:
            - "*"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-linux
      - build-mac