name: Gradle Libraries Update
on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:
jobs:
  create-update-branch:
    name: "Create Update Branch"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '25'
      - uses: c-hive/gha-yarn-cache@v2
        with:
          directory: kotlin-js-store
      - uses: burrunan/gradle-cache-action@v1
        name: Update Deps
        with:
          arguments: useLatestVersions :jsmints-plugins:useLatestVersions
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "create-pull-request/${{github.job}}/${{github.run_id}}"
          commit-message: "[create-pull-request] ${{github.workflow}}"
          token: ${{ secrets.TESTMINTS_PAT }}
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.TESTMINTS_PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase
