name: Gradle Libraries Update
on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:
jobs:
  create-update-branch:
    name: "Create Update Branch"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '25'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true
      - name: Update Deps
        run: ./gradlew versionCatalogUpdate --no-configuration-cache
      - name: Clean
        run: ./gradlew clean
      - name: Update Yarn Lock
        run: ./gradlew kotlinUpgradeYarnLock --no-configuration-cache --no-build-cache
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "cpr-gradle-update/${{github.job}}/${{github.run_id}}"
          commit-message: "[patch] ${{github.workflow}}"
          token: ${{ secrets.TESTMINTS_PAT }}
          delete-branch: true
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.TESTMINTS_PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase
