name: Build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
jobs:
  build-job:
    name: "Build"
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.TESTMINTS_PAT }}
      GITHUB_TOKEN: ${{ secrets.TESTMINTS_PAT }}
      GRGIT_USER: ${{ secrets.TESTMINTS_PAT }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: robertfmurdock
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
      - name: Generate Version 🧮
        run: ./gradlew calculateVersion -PexportToGithub=true --scan
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: Build 🔨
        run: ./gradlew release check -Pversion=${{ env.TAGGER_VERSION }} --no-configuration-cache --scan
#      - name: Plugin Publish 🙏
#        run: ./gradlew -p wdio-test-plugin publish -Pversion=${{ env.TAGGER_VERSION }} --no-configuration-cache --scan
      - name: Push result to Testspace server
        if: always()
        run: |
          testspace $(find . -path *test-results* -name *.xml)
      - name: Collect Test Results
        if: ${{ always() }}
        run: ./gradlew collectResults
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-output
          path: |
            build/test-output/
