name: Build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build-job:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - run: cat /etc/hosts
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: c-hive/gha-yarn-cache@v2
        with:
          directory: kotlin-js-store
      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          arguments: check
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-output
          path: |
            build/test-output/
